import { DatasourceType } from '@src/domain/types/datasources.type';

export const Datasources: DatasourceType = {
  CHARACTER_REPOSITORY: 'CHARACTER_REPOSITORY',
  INVITE_REPOSITORY: 'INVITE_REPOSITORY',
  ITEM_REPOSITORY: 'ITEM_REPOSITORY',
  SESSION_REPOSITORY: 'SESSION_REPOSITORY',
  USER_REPOSITORY: 'USER_REPOSITORY',
};
